name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun check
      - run: bun types
      - run: bun run test # Skips tests inside templates.
      - run: bun test
        working-directory: plugin/icon
      - run: bun test
        working-directory: plugin/android-sdk
      - uses: tobua/release-npm-action@v3
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
