name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: npm install --legacy-peer-deps
      - name: 🧪 Test
        run: npm test
      - name: 🚧 Build
        run: npm run build
      - uses: tobua/release-npm-action@v2
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
