name: release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/setup-node@v7
        with:
          node-version: 26
      - uses: actions/checkout@v7
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun check
      - run: bun types
      - run: bun run test # Skips tests inside templates.
      - run: bun test
        working-directory: plugin/icon
      - run: bun test
        working-directory: plugin/android-sdk
      - uses: tobua/release-npm-action@v5
